<a href="https://colab.research.google.com/github/nv-hiep/pyspark/blob/main/pyspark_course_GL_RecommendationEngine_with_MusicData.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import os

# innstall java
!apt-get install openjdk-8-jdk-headless -qq > /dev/null

# install spark (change the version number if needed)
if not os.path.exists('/content/spark-3.1.1-bin-hadoop3.2.tgz'):
  !wget -q http://archive.apache.org/dist/spark/spark-3.1.1/spark-3.1.1-bin-hadoop3.2.tgz
  
  # unzip the spark file to the current folder
  !tar xf spark-3.1.1-bin-hadoop3.2.tgz

# set your spark folder to your system path environment. 
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-8-openjdk-amd64"
os.environ["SPARK_HOME"] = "/content/spark-3.1.1-bin-hadoop3.2"


# install findspark using pip
!pip install -q findspark

In [2]:
# For python users, you should also install pyspark using the following command.
# !pip install pyspark

Run a local spark session to test your installation:

In [3]:
import findspark
findspark.init()

from pyspark import SparkContext
from pyspark.sql import SparkSession, Window, Row

from pyspark.sql.functions import *
from pyspark.sql.types import *
import matplotlib.pyplot as plt

#https://spark.apache.org/docs/latest/sql-getting-started.html
# spark = SparkSession.builder.master("local[*]").getOrCreate()
spark = SparkSession.builder.appName('PySpark').getOrCreate()
# spark = SparkSession.builder.appName('PySpark').enableHiveSupport().getOrCreate()

spark.conf.set('spark.sql.repl.eagerEval.enabled', True) # Property used to format output tables better


# spark = SparkSession.builder.appName('PySpark').master("local[1]").config("spark.sql.catalogImplementation","hive").enableHiveSupport().getOrCreate()
# spark.conf.set("spark.sql.catalogImplementation","hive")
# spark.conf.set('spark.sql.sources.default', 'delta')
# spark.conf.set('spark.sql.legacy.createHiveTableByDefault', False)
# spark.conf.set('spspark.sql.hive.convertCTAS', True)

spark

In [4]:
import numpy as np
import pandas as pd
from scipy.sparse import csr_matrix

# display results to 3 decimal points, not in scientific notation
pd.set_option('display.float_format', lambda x: '%.3f' % x)

In [5]:
# from pyspark.sql.functions import udf
# from pyspark.sql.types import IntegerType
import urllib.request

In [79]:
# ! rm -rf spark-3.1.1-bin-hadoop3.2.tgz

In [7]:
!ls

data	     lastfm.zip   spark-3.1.1-bin-hadoop3.2
kaggle.json  sample_data  spark-3.1.1-bin-hadoop3.2.tgz


In [8]:
from pyspark.ml.classification import LogisticRegression

# Connect to Kaggle

Ref: https://galhever.medium.com/how-to-import-data-from-kaggle-to-google-colab-8160caa11e2

Install the Kaggle package that will be used for importing the data.

In [9]:
!pip install kaggle

Next, we need to upload the credentials of our Kaggle account. To do so, you need to enter your profile and “Create New API Token”. If you already have one you can click on “Expire API Token” and create a new one.

Then, save the json file with your credentials on your computer and upload this file to Colab using the code below:

In [10]:
from google.colab import files

if not os.path.exists('/content/kaggle.json'):
  files.upload()

The Kaggle API client expects the json file to be in ~/.kaggle folder so let’s create a new folder and move it inside.

In [11]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

Next, we will click on the three vertical points on the right side of the screen and “Copy the API Command” of the dataset that we want to import from Kaggle.

In [12]:
# !kaggle datasets download -d jessicali9530/celeba-dataset
# !kaggle datasets download -d hesh97/titanicdataset-traincsv
! kaggle datasets download -d neferfufi/lastfm

lastfm.zip: Skipping, found more recently modified local copy (use --force to force download)


In [13]:
!pwd

/content


Let’s see the imported files:

In [14]:
!ls

data	     lastfm.zip   spark-3.1.1-bin-hadoop3.2
kaggle.json  sample_data  spark-3.1.1-bin-hadoop3.2.tgz


Now, the last step is to open the extracted files and get the data:

In [15]:
import zipfile
zip_ref = zipfile.ZipFile('lastfm.zip', 'r')
zip_ref.extractall('data')
zip_ref.close()

In [16]:
!ls

data	     lastfm.zip   spark-3.1.1-bin-hadoop3.2
kaggle.json  sample_data  spark-3.1.1-bin-hadoop3.2.tgz


In [17]:
# ! rm -rf titanicdataset-traincsv.zip

In [18]:
# !ls

In [19]:
% cd data

/content/data


In [20]:
!ls

userid-profile.csv				  usersha1-profile.csv
userid-timestamp-artid-artname-traid-traname.tsv  usersha1-profile.tsv
usersha1-artmbid-artname-plays.tsv


That’s it! Now your data is ready and you can start working on it.

# Read userid_profile data

In [21]:
DATA_PATH = '/content/'
DATA_DIR  = os.path.join(DATA_PATH, 'data')

In [22]:
if not os.path.exists(DATA_DIR):
  os.mkdir(DATA_DIR)

In [23]:
# url = 'https://storage.googleapis.com/kaggle-data-sets/50119/92017/compressed/userid-timestamp-artid-artname-traid-traname.tsv.zip?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gcp-kaggle-com%40kaggle-161607.iam.gserviceaccount.com%2F20210724%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20210724T145658Z&X-Goog-Expires=259199&X-Goog-SignedHeaders=host&X-Goog-Signature=95a835e0400112e6132be28d12009dec126eab889e0c98f15c46ed9ff843d435150e8006991a7cf518a97bb49bfd110d6c732fb6bbb42156221abd376a466cea004e79dfdb16aeef9d0049442e221a6ff07d9580aa2aa0e1281e0cea1f81c2584d9b654da5d2eb59fa04eb78dd94b0d7f1c93c851efdeec15765a54269b45a99cd09546bcb18b6f9e7d0924e273637ff7d729a715b0b1f774862ced30b9f16ddefdb326af90f4b997f1bc600a3c4442080885a546e26252a8bea6d1f057be19476a60bf1651499ca524fcd3a5bc8180b7fe828fa91680d7907a45a2c9cef38c00d4a602a6524986a1978546bd2ea30af22eaa562aa818e5868ae552599d8888c'
# datfile = os.path.join( DATA_DIR, os.path.split(url)[-1])

# if not os.path.exists(datfile):
#   filename, headers = urllib.request.urlretrieve(url, datfile)

In [24]:
! ls

userid-profile.csv				  usersha1-profile.csv
userid-timestamp-artid-artname-traid-traname.tsv  usersha1-profile.tsv
usersha1-artmbid-artname-plays.tsv


In [25]:
user_profile = pd.read_csv( os.path.join(DATA_DIR, 'userid-profile.csv'), sep=',' )
user_profile.head()

#id gender    age        country    registered
0  user_000001      m    nan          Japan  Aug 13, 2006
1  user_000002      f    nan           Peru  Feb 24, 2006
2  user_000003      m 22.000  United States  Oct 30, 2005
3  user_000004      f    nan            NaN  Apr 26, 2006
4  user_000005      m    nan       Bulgaria  Jun 29, 2006

In [26]:
user_profile.columns

Index(['#id', 'gender', 'age', 'country', 'registered'], dtype='object')

In [27]:
user_profile.describe()

age
count 286.000
mean   25.367
std     8.315
min     3.000
25%    21.000
50%    23.000
75%    28.000
max   103.000

In [28]:
user_profile.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 992 entries, 0 to 991
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   #id         992 non-null    object 
 1   gender      884 non-null    object 
 2   age         286 non-null    float64
 3   country     907 non-null    object 
 4   registered  984 non-null    object 
dtypes: float64(1), object(4)
memory usage: 38.9+ KB


In [29]:
# Check null values
user_profile.isnull().sum(axis = 0)

#id             0
gender        108
age           706
country        85
registered      8
dtype: int64

In [30]:
user_profile.gender.value_counts()

m    502
f    382
Name: gender, dtype: int64

In [31]:
user_profile.country.value_counts()

United States               228
United Kingdom              126
Poland                       50
Germany                      36
Norway                       35
                           ... 
Cote D'Ivoire                 1
India                         1
Armenia                       1
Algeria                       1
Northern Mariana Islands      1
Name: country, Length: 66, dtype: int64

In [32]:
user_profile.registered.value_counts()

Dec 6, 2005     6
Apr 18, 2006    5
Mar 5, 2006     5
Dec 19, 2006    5
Jan 22, 2006    5
               ..
Aug 26, 2004    1
Jan 13, 2005    1
Jul 23, 2006    1
Apr 2, 2004     1
Oct 29, 2006    1
Name: registered, Length: 625, dtype: int64

# Load user data

In [33]:
data_file = os.path.join( DATA_DIR, 'usersha1-artmbid-artname-plays.tsv' )
user_data = pd.read_csv( data_file, sep='\t', header=None )
user_data.head()

0  ...     3
0  00000c289a1829a808ac09c00daf10bc3c4e223b  ...  2137
1  00000c289a1829a808ac09c00daf10bc3c4e223b  ...  1099
2  00000c289a1829a808ac09c00daf10bc3c4e223b  ...   897
3  00000c289a1829a808ac09c00daf10bc3c4e223b  ...   717
4  00000c289a1829a808ac09c00daf10bc3c4e223b  ...   706

[5 rows x 4 columns]

In [34]:
user_data.columns = ['user_id', 'musicbrainz-artist-id', 'artist-name', 'plays']

In [35]:
user_data.head()

user_id  ... plays
0  00000c289a1829a808ac09c00daf10bc3c4e223b  ...  2137
1  00000c289a1829a808ac09c00daf10bc3c4e223b  ...  1099
2  00000c289a1829a808ac09c00daf10bc3c4e223b  ...   897
3  00000c289a1829a808ac09c00daf10bc3c4e223b  ...   717
4  00000c289a1829a808ac09c00daf10bc3c4e223b  ...   706

[5 rows x 4 columns]

In [36]:
user_data.isnull().sum()

user_id                       0
musicbrainz-artist-id    226137
artist-name                 204
plays                         0
dtype: int64

In [37]:
user_data[ user_data['artist-name'].isnull() ].head()

user_id  ... plays
244853  039e5d61d65bbf5e6d95b07b1b3b67f7fd287a62  ...    18
431015  065a001be5a8a55971042077933e263d0d5cde46  ...   186
455721  06b17c50402d06a497cb13a0375992fd1e90b392  ...     3
504026  0757ac29973aab69bb31cd164c6df975bf4df9a1  ...    38
607282  08e102b376abe856a3d4be5ea14ad6b37395fe82  ...   208

[5 rows x 4 columns]

In [38]:
# Drop all rows where artist-name is null
if user_data['artist-name'].isnull().sum() > 0:
  user_data.dropna( axis=0, subset=['artist-name'], inplace=True )

In [39]:
user_data[ user_data['artist-name'].isnull() ]

Empty DataFrame
Columns: [user_id, musicbrainz-artist-id, artist-name, plays]
Index: []

In [40]:
user_data['artist-name'].isnull().sum()

0

In [41]:
user_data.head()

user_id  ... plays
0  00000c289a1829a808ac09c00daf10bc3c4e223b  ...  2137
1  00000c289a1829a808ac09c00daf10bc3c4e223b  ...  1099
2  00000c289a1829a808ac09c00daf10bc3c4e223b  ...   897
3  00000c289a1829a808ac09c00daf10bc3c4e223b  ...   717
4  00000c289a1829a808ac09c00daf10bc3c4e223b  ...   706

[5 rows x 4 columns]

In [42]:
user_data['artist-name'].unique()

array(['betty blowtorch', 'die Ärzte', 'melissa etheridge', ...,
       'sacred buddha', 'cat lunette', 'suzanina'], dtype=object)

In [43]:
user_data['artist-name'].nunique()

292363

In [44]:
user_data['artist-name'].value_counts()

radiohead                           77254
the beatles                         76245
coldplay                            66658
red hot chili peppers               48924
muse                                46954
                                    ...  
path of annihilation                    1
kنrtsy hatakka & kimmo kajasto          1
eric dodge                              1
yann tiersen & the divine comedy        1
the good                                1
Name: artist-name, Length: 292363, dtype: int64

In [45]:
artist_plays = user_data.groupby( ['artist-name'] ).sum().reset_index().rename( columns={'plays' : 'total_plays'} )
artist_plays.head()

artist-name  total_plays
0                                       04)]            6
1                                         2          1606
2                                  58725ab=>           23
3   80lİ yillarin tÜrkÇe sÖzlÜ aŞk Şarkilari           70
4                              amy winehouse           23

In [46]:
user_data_with_artist_plays = user_data.merge( artist_plays, left_on='artist-name', right_on='artist-name', how='left' )

In [47]:
user_data_with_artist_plays.head()

user_id  ... total_plays
0  00000c289a1829a808ac09c00daf10bc3c4e223b  ...       25651
1  00000c289a1829a808ac09c00daf10bc3c4e223b  ...     3704875
2  00000c289a1829a808ac09c00daf10bc3c4e223b  ...      180391
3  00000c289a1829a808ac09c00daf10bc3c4e223b  ...      410725
4  00000c289a1829a808ac09c00daf10bc3c4e223b  ...       90498

[5 rows x 5 columns]

In [48]:
artist_plays.total_plays.describe()

count     292363.000
mean       12907.022
std       185981.631
min            1.000
25%           53.000
50%          208.000
75%         1048.000
max     30466827.000
Name: total_plays, dtype: float64

In [49]:
artist_plays[ artist_plays.total_plays == artist_plays.total_plays.max() ]

artist-name  total_plays
252494  the beatles     30466827

In [50]:
artist_plays.total_plays.quantile( np.arange(0.9, 1., 0.02) )

0.900    6137.800
0.920    9102.040
0.940   14898.000
0.960   28420.120
0.980   79403.560
Name: total_plays, dtype: float64

In [51]:
artist_plays.total_plays.value_counts()

1        2816
2        2724
3        2365
4        2211
5        2123
         ... 
52887       1
40605       1
36511       1
67246       1
21621       1
Name: total_plays, Length: 28112, dtype: int64

In [52]:
# Only top artist
thresh = 100000
top_artist = user_data_with_artist_plays.query( 'total_plays >= @thresh' )
top_artist.drop('musicbrainz-artist-id', axis=1).head()

user_id  ... total_plays
1  00000c289a1829a808ac09c00daf10bc3c4e223b  ...     3704875
2  00000c289a1829a808ac09c00daf10bc3c4e223b  ...      180391
3  00000c289a1829a808ac09c00daf10bc3c4e223b  ...      410725
5  00000c289a1829a808ac09c00daf10bc3c4e223b  ...    13547741
7  00000c289a1829a808ac09c00daf10bc3c4e223b  ...     1004743

[5 rows x 4 columns]

In [53]:
user_data_with_artist_plays.head()

user_id  ... total_plays
0  00000c289a1829a808ac09c00daf10bc3c4e223b  ...       25651
1  00000c289a1829a808ac09c00daf10bc3c4e223b  ...     3704875
2  00000c289a1829a808ac09c00daf10bc3c4e223b  ...      180391
3  00000c289a1829a808ac09c00daf10bc3c4e223b  ...      410725
4  00000c289a1829a808ac09c00daf10bc3c4e223b  ...       90498

[5 rows x 5 columns]

# Read user_profiles data

In [54]:
data_file = os.path.join( DATA_DIR, 'usersha1-profile.tsv' )
user_profiles = pd.read_csv(data_file, sep='\t', header=None)
user_profiles.head()

0    1  ...              3             4
0  00000c289a1829a808ac09c00daf10bc3c4e223b    f  ...        Germany   Feb 1, 2007
1  00001411dc427966b17297bf4d69e7e193135d89    f  ...         Canada   Dec 4, 2007
2  00004d2ac9316e22dc007ab2243d6fcb239e707d  NaN  ...        Germany   Sep 1, 2006
3  000063d3fe1cf2ba248b9e3c3f0334845a27a6bf    m  ...         Mexico  Apr 28, 2008
4  00007a47085b9aab8af55f52ec8846ac479ac4fe    m  ...  United States  Jan 27, 2006

[5 rows x 5 columns]

In [55]:
user_profiles.columns = ['user', 'gender', 'age', 'country', 'registered']
user_profiles.head()

user gender  ...        country    registered
0  00000c289a1829a808ac09c00daf10bc3c4e223b      f  ...        Germany   Feb 1, 2007
1  00001411dc427966b17297bf4d69e7e193135d89      f  ...         Canada   Dec 4, 2007
2  00004d2ac9316e22dc007ab2243d6fcb239e707d    NaN  ...        Germany   Sep 1, 2006
3  000063d3fe1cf2ba248b9e3c3f0334845a27a6bf      m  ...         Mexico  Apr 28, 2008
4  00007a47085b9aab8af55f52ec8846ac479ac4fe      m  ...  United States  Jan 27, 2006

[5 rows x 5 columns]

In [56]:
combined = top_artist.merge( user_profiles, left_on='user_id', right_on='user', how='left' ).drop( ['musicbrainz-artist-id', 'user_id'], axis=1 )
combined.head()

artist-name  plays  total_plays  ...    age  country   registered
0                die Ärzte   1099      3704875  ... 22.000  Germany  Feb 1, 2007
1        melissa etheridge    897       180391  ... 22.000  Germany  Feb 1, 2007
2                elvenking    717       410725  ... 22.000  Germany  Feb 1, 2007
3    red hot chili peppers    691     13547741  ... 22.000  Germany  Feb 1, 2007
4  the black dahlia murder    507      1004743  ... 22.000  Germany  Feb 1, 2007

[5 rows x 8 columns]

In [57]:
# Artists from USA
usa_data = combined.query( "country == 'United States'" )
usa_data.head()

artist-name  plays  total_plays  ...    age        country    registered
134   devendra banhart    456      2366807  ... 28.000  United States  Jan 27, 2006
135   boards of canada    407      6115545  ... 28.000  United States  Jan 27, 2006
136          cocorosie    386      2194862  ... 28.000  United States  Jan 27, 2006
137         aphex twin    213      4248296  ... 28.000  United States  Jan 27, 2006
138  animal collective    203      3495537  ... 28.000  United States  Jan 27, 2006

[5 rows x 8 columns]

In [58]:
combined.query( 'total_plays > @thresh' ).head()

artist-name  plays  total_plays  ...    age  country   registered
0                die Ärzte   1099      3704875  ... 22.000  Germany  Feb 1, 2007
1        melissa etheridge    897       180391  ... 22.000  Germany  Feb 1, 2007
2                elvenking    717       410725  ... 22.000  Germany  Feb 1, 2007
3    red hot chili peppers    691     13547741  ... 22.000  Germany  Feb 1, 2007
4  the black dahlia murder    507      1004743  ... 22.000  Germany  Feb 1, 2007

[5 rows x 8 columns]

In [59]:
combined.query('plays > 100000').head()

artist-name   plays  ...             country    registered
30579             lil wayne  107758  ...       United States  May 12, 2008
138529   christina aguilera  135392  ...              Brazil   Sep 1, 2007
483528         alice cooper  134993  ...      United Kingdom  Aug 10, 2005
549862            in flames  112989  ...  Russian Federation  Sep 19, 2007
1032662         dean martin  288375  ...       United States  Apr 26, 2006

[5 rows x 8 columns]

In [60]:
initial_rows = usa_data.shape[0]

In [61]:
print('Initial number of rows: ', initial_rows)

Initial number of rows:  2525274


In [62]:
# drop duplicates
usa_data_2 = usa_data.drop_duplicates( subset=['user', 'artist-name'] )
usa_data_2.head()

artist-name  plays  total_plays  ...    age        country    registered
134   devendra banhart    456      2366807  ... 28.000  United States  Jan 27, 2006
135   boards of canada    407      6115545  ... 28.000  United States  Jan 27, 2006
136          cocorosie    386      2194862  ... 28.000  United States  Jan 27, 2006
137         aphex twin    213      4248296  ... 28.000  United States  Jan 27, 2006
138  animal collective    203      3495537  ... 28.000  United States  Jan 27, 2006

[5 rows x 8 columns]

In [63]:
current_rows = usa_data_2.shape[0]
print('Number of current rows: ', current_rows)
print('Current shape: ', usa_data_2.shape)

Number of current rows:  2525268
Current shape:  (2525268, 8)


In [64]:
print( f'Removed {initial_rows - current_rows} rows' )

Removed 6 rows


In [65]:
del usa_data
del combined
del top_artist
del user_data_with_artist_plays
del artist_plays
del user_data
del user_profiles
del user_profile

# Reshape data into sparse matrix

In [66]:
wide_artist_data = usa_data_2.pivot(index='artist-name', columns='user', values='plays').fillna(0)
# wide_artist_data.head()

In [80]:
del usa_data_2

In [67]:
print(wide_artist_data.shape)
# wide_artist_data.head(1)
wide_artist_data.iloc[0]

(4913, 66881)


user
00007a47085b9aab8af55f52ec8846ac479ac4fe   0.000
0001a57568309b287363e72dc682e9a170ba6dc2   0.000
00024b5b85c40f990c28644d53257819980bf6bb   0.000
0002dd2154072434d26e5409faa591bfb260a01e   0.000
00032c7933e0eb05f2258f1147ef81a90f2d4d6c   0.000
                                            ... 
fff9dc65e7f2763a7e8bce8d99cc1491c2ae4c6f   0.000
fffa9294e858a7c863b5ad363c748c2330d9bd45   0.000
fffa9d62caff0f038c7a35db70f109b1bba04a1d   0.000
fffaf6f9a1a3ad8bd0dff7b48b2eb9eef030fdee   0.000
fffe8c7f952d9b960a56ed4dcb40a415d924b224   0.000
Name: !!!, Length: 66881, dtype: float64

In [68]:
wide_artist_data.values.shape

(4913, 66881)

In [165]:
wide_artist_data_sparse = csr_matrix(wide_artist_data.values)

In [166]:
print(wide_artist_data_sparse.shape)
print(wide_artist_data_sparse[1].shape)
wide_artist_data_sparse[1].data

(4913, 66881)
(1, 66881)


array([305.,  31.,  66., 251.,  21.,  47.,  27.,  32.])

In [71]:
print( type( wide_artist_data_sparse ) )
# print( wide_artist_data_sparse.toarray() ) # dont run -> out-of-RAM
print( wide_artist_data_sparse[1, :] )

<class 'scipy.sparse.csr.csr_matrix'>
  (0, 11695)	305.0
  (0, 15536)	31.0
  (0, 28950)	66.0
  (0, 31107)	251.0
  (0, 33859)	21.0
  (0, 36850)	47.0
  (0, 44046)	27.0
  (0, 48038)	32.0


In [73]:
print( wide_artist_data_sparse[0, :] )

  (0, 23)	113.0
  (0, 50)	109.0
  (0, 185)	127.0
  (0, 194)	587.0
  (0, 199)	139.0
  (0, 421)	128.0
  (0, 475)	3.0
  (0, 596)	222.0
  (0, 636)	6.0
  (0, 1060)	89.0
  (0, 1198)	52.0
  (0, 1417)	23.0
  (0, 1584)	463.0
  (0, 1596)	206.0
  (0, 1652)	17.0
  (0, 1665)	327.0
  (0, 1669)	336.0
  (0, 2010)	142.0
  (0, 2099)	63.0
  (0, 2282)	7.0
  (0, 2410)	232.0
  (0, 2844)	262.0
  (0, 2928)	38.0
  (0, 3005)	150.0
  (0, 3380)	157.0
  :	:
  (0, 64286)	226.0
  (0, 64287)	491.0
  (0, 64291)	223.0
  (0, 64340)	128.0
  (0, 64360)	67.0
  (0, 64377)	81.0
  (0, 64392)	625.0
  (0, 64536)	64.0
  (0, 64824)	41.0
  (0, 65105)	46.0
  (0, 65398)	47.0
  (0, 65446)	69.0
  (0, 65473)	10.0
  (0, 65537)	133.0
  (0, 65660)	28.0
  (0, 65704)	229.0
  (0, 65738)	284.0
  (0, 65907)	76.0
  (0, 65914)	73.0
  (0, 65985)	24.0
  (0, 66045)	451.0
  (0, 66143)	31.0
  (0, 66433)	17.0
  (0, 66729)	111.0
  (0, 66865)	86.0


In [76]:
wide_artist_data_sparse[0, :].data.shape

(653,)

In [72]:
print( wide_artist_data_sparse.shape )
print( wide_artist_data_sparse.data.shape )

(4913, 66881)
(2525268,)


# Recommendation Engine with KNN model

In [77]:
from sklearn.neighbors import NearestNeighbors

In [149]:
knn_model = NearestNeighbors( metric= 'cosine', algorithm='brute' )

In [81]:
knn_model

NearestNeighbors(algorithm='brute', leaf_size=30, metric='cosine',
                 metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                 radius=1.0)

In [173]:
knn_model.fit(wide_artist_data_sparse)

NearestNeighbors(algorithm='brute', leaf_size=30, metric='cosine',
                 metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                 radius=1.0)

In [174]:
random_id = np.random.choice(wide_artist_data_sparse.shape[0])
random_id

803

In [175]:
wide_artist_data.iloc[random_id, :].values.reshape(1,-1)

array([[0., 0., 0., ..., 0., 0., 0.]])

In [176]:
del random_id
# wide_artist_data.index == 'the beatles'
query_id = wide_artist_data.index.get_loc('the beatles')
query_id

4104

In [180]:
distances, indices = knn_model.kneighbors( wide_artist_data.iloc[query_id, :].values.reshape(1,-1), n_neighbors=6 )
print( distances )
print(indices)

[[0.         0.55010107 0.60371909 0.6436559  0.67470267 0.67533617]]
[[4104 2225 1721 4377 2508 3266]]


In [181]:
wide_artist_data.head(1)

user         00007a47085b9aab8af55f52ec8846ac479ac4fe  ...  fffe8c7f952d9b960a56ed4dcb40a415d924b224
artist-name                                            ...                                          
!!!                                             0.000  ...                                     0.000

[1 rows x 66881 columns]

In [182]:
wide_artist_data[wide_artist_data.index == 'the beatles']

user         00007a47085b9aab8af55f52ec8846ac479ac4fe  ...  fffe8c7f952d9b960a56ed4dcb40a415d924b224
artist-name                                            ...                                          
the beatles                                     0.000  ...                                     0.000

[1 rows x 66881 columns]

In [183]:
# wide_artist_data.loc['the beatles']

In [184]:
print( 'Recommendations for {}: '.format(wide_artist_data.index[query_id]) )
for i, (d,idx) in enumerate(zip(distances.flatten(), indices.flatten() )):
  print( '{0} : {1}, with distance of {2}'.format( i, wide_artist_data.index[idx], d ) )

Recommendations for the beatles: 
0 : the beatles, with distance of 0.0
1 : john lennon, with distance of 0.5501010696937427
2 : george harrison, with distance of 0.6037190893907172
3 : the rolling stones, with distance of 0.6436559034790297
4 : led zeppelin, with distance of 0.6747026657155826
5 : paul mccartney, with distance of 0.6753361725955604


In [185]:
def print_recommendations(query_id):
  distances, indices = knn_model.kneighbors(wide_artist_data.iloc[query_id, :].values.reshape(1, -1), n_neighbors = 6)
  for i, (d,idx) in enumerate(zip(distances.flatten(), indices.flatten() )):
    if i == 0:
      print('Recommendations with binary play data for "{}": '.format(wide_artist_data.index[query_id]) )
    else:
      print( '{0} : {1}, with distance of {2}'.format( i, wide_artist_data.index[idx], d ) )

In [186]:
artist_name = 'michael jackson'
query_id = wide_artist_data.index.get_loc(artist_name)
query_id

2857

In [187]:
print_recommendations(query_id)

Recommendations with binary play data for "michael jackson": 
1 : janet jackson, with distance of 0.7144134422445221
2 : mariah carey, with distance of 0.7332984300057374
3 : air supply, with distance of 0.7555041640219585
4 : shakira, with distance of 0.7677839870558588
5 : luther vandross, with distance of 0.7760306765049969


In [188]:
del wide_artist_data_sparse

# Make all plays count binary

In [189]:
wide_artist_data_zero_one = wide_artist_data.apply(np.sign)

In [198]:
wide_artist_data_zero_one.iloc[0,:].unique()

array([0., 1.])

In [190]:
wide_artist_data_zero_one_sparse = csr_matrix(wide_artist_data_zero_one.values)

In [192]:
wide_artist_data_zero_one.head(1)

user         00007a47085b9aab8af55f52ec8846ac479ac4fe  ...  fffe8c7f952d9b960a56ed4dcb40a415d924b224
artist-name                                            ...                                          
!!!                                             0.000  ...                                     0.000

[1 rows x 66881 columns]

In [201]:
wide_artist_data_zero_one_sparse[1].data

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [202]:
wide_artist_data_zero_one_sparse[0].data

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.

In [204]:
knn_model.fit(wide_artist_data_zero_one_sparse)

NearestNeighbors(algorithm='brute', leaf_size=30, metric='cosine',
                 metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                 radius=1.0)

In [206]:
query_id = 4104
distances, indices = knn_model.kneighbors( wide_artist_data.iloc[query_id, :].values.reshape(1,-1), n_neighbors=6 )
print( distances )
print(indices)

[[0.58816594 0.73219915 0.75975395 0.76897394 0.77151376 0.77785163]]
[[4104 2225 1721 2508  610 4377]]


In [207]:
print( 'Recommendations for {}: '.format(wide_artist_data.index[query_id]) )
for i, (d,idx) in enumerate(zip(distances.flatten(), indices.flatten() )):
  print( '{0} : {1}, with distance of {2}'.format( i, wide_artist_data.index[idx], d ) )

Recommendations for the beatles: 
0 : the beatles, with distance of 0.588165942306397
1 : john lennon, with distance of 0.7321991540391699
2 : george harrison, with distance of 0.759753945641315
3 : led zeppelin, with distance of 0.7689739411445019
4 : bob dylan, with distance of 0.7715137610412005
5 : the rolling stones, with distance of 0.7778516289247016


In [208]:
artist_name = 'joe budden'
query_id = wide_artist_data.index.get_loc(artist_name)
query_id

2204

In [209]:
distances, indices = knn_model.kneighbors( wide_artist_data.iloc[query_id, :].values.reshape(1,-1), n_neighbors=6 )
print( distances )
print(indices)

[[0.60966495 0.83131005 0.83297916 0.83514194 0.83527714 0.8404956 ]]
[[2204 3238 2108 1517 2276 3599]]


In [210]:
print( 'Recommendations for {}: '.format(wide_artist_data.index[query_id]) )
for i, (d,idx) in enumerate(zip(distances.flatten(), indices.flatten() )):
  print( '{0} : {1}, with distance of {2}'.format( i, wide_artist_data.index[idx], d ) )

Recommendations for joe budden: 
0 : joe budden, with distance of 0.609664951774953
1 : papoose, with distance of 0.8313100548529462
2 : jadakiss, with distance of 0.8329791563395482
3 : fabolous, with distance of 0.8351419409228308
4 : juelz santana, with distance of 0.8352771425507504
5 : saigon, with distance of 0.8404956041043072


In [211]:
artist_name = 'see-saw'
query_id = wide_artist_data.index.get_loc(artist_name)
query_id

3676

In [212]:
print( 'Recommendations for {}: '.format(wide_artist_data.index[query_id]) )
for i, (d,idx) in enumerate(zip(distances.flatten(), indices.flatten() )):
  print( '{0} : {1}, with distance of {2}'.format( i, wide_artist_data.index[idx], d ) )

Recommendations for see-saw: 
0 : joe budden, with distance of 0.609664951774953
1 : papoose, with distance of 0.8313100548529462
2 : jadakiss, with distance of 0.8329791563395482
3 : fabolous, with distance of 0.8351419409228308
4 : juelz santana, with distance of 0.8352771425507504
5 : saigon, with distance of 0.8404956041043072
